### ISSUE TITLE
[BUG] 使用测试版 OAuth 刷新令牌有效期短

### ISSUE THREAD

**Issue by Jared-02** [Jared-02/auto-backup#1]
- [测试版 OAuth 同意屏幕，刷新令牌有效期仅为 7 天](https://developers.google.com/identity/protocols/oauth2#expiration)，需要频繁重新授权，不利于长期自动化部署。
- [正式版 OAuth 同意屏幕不允许使用 OOB（手动复制粘贴选项）流程](https://developers.google.com/identity/protocols/oauth2/resources/oob-migration)，故而弃用 `桌面应用` 应用类型，迁移到 `Web 应用` 类型，使用重定向 URI 授权。

**Comment by Jared-02** [comment]
示例 Error：
```
oauth2client.client.HttpAccessTokenRefreshError: invalid_grant: Token has been expired or revoked.
...
pydrive2.auth.RefreshError: Access token refresh failed: invalid_grant: Token has been expired or revoked.
```

**Comment by wanyunr** [comment]
好像还是不行
![image](https://github.com/Jared-02/auto-backup/assets/105478325/45e6500c-5794-4b95-94af-fb69b5dbdfbb)

![image](https://github.com/Jared-02/auto-backup/assets/105478325/48d065b2-e35f-45d9-ab31-5dd64e12b452)

**还是报错400**
![Clip_2024-03-17_23-27-22](https://github.com/Jared-02/auto-backup/assets/105478325/467f8f12-b79c-421e-8965-f1254b1e4195)

**Comment by Jared-02** [comment]
https://github.com/Jared-02/auto-backup/issues/1#issuecomment-2002509207

你可能忽略了这一步骤：
> 如果你的脚本运行环境在远程服务器，你需要通过 SSH 隧道转发本地端口以完成重定向验证：
>  ```
>  ssh -L 8080:localhost:8080 root@8.8.8.8 -N
> ```
> *如果使用密钥登录：*
> ```
> ssh -i path/to/key -L 8080:localhost:8080 root@8.8.8.8 -N
> ```

**Comment by wanyunr** [comment]
> [#1 (comment)](https://github.com/Jared-02/auto-backup/issues/1#issuecomment-2002509207)
> 
> 你可能忽略了这一步骤：
> 
> > 如果你的脚本运行环境在远程服务器，你需要通过 SSH 隧道转发本地端口以完成重定向验证：
> > ```
> > ssh -L 8080:localhost:8080 root@8.8.8.8 -N
> > ```
> >     
> >   
> > _如果使用密钥登录：_
> > ```
> > ssh -i path/to/key -L 8080:localhost:8080 root@8.8.8.8 -N
> > 

在本地启动端口转发后还是一样报错
使用xhell或者termius自带的端口转发也一直没尝试成功）
![Clip_2024-03-18_02-21-07](https://github.com/Jared-02/auto-backup/assets/105478325/1f41f25e-259b-4fb0-9985-5dbd361e0202)

**Comment by Jared-02** [comment]
抱歉，排查了一下，原因应该是代码第 30 行有修改你没有同步：
https://github.com/Jared-02/auto-backup/blob/c8ed9a436f808a287afe8588b3979ff3323dfbc3/gd_backup.py#L30

**Comment by wanyunr** [comment]
检查了一下，应该不是这个原因
在另一台服务器上也尝试了，依旧是`错误 400： redirect_uri_mismatch`

是这样开一个隧道，然后再连接服务器操作授权吗(连接上后卡在那，没有其他响应)
![Clip_2024-03-18_03-06-18](https://github.com/Jared-02/auto-backup/assets/105478325/00f1a200-ca4d-492c-a8bc-0d270cfb4580)

**Comment by Jared-02** [comment]
流程应该是先开隧道，然后 `python gd_backup.py`，脚本提示一个链接进行验证，登录 google 账号，最后会自动跳转 `localhost:8080` 完成验证。

建议你还是检查一下脚本第 30 行，如果只是隧道设置错误会提示找不到 localhost:8080，不会提示 `错误 400： redirect_uri_mismatch`

**Comment by Jared-02** [comment]
我这边复现是这样三种情况：

`gauth.LocalWebserverAuth()` + 桌面应用凭据 =  localhost 拒绝了我们的连接请求
  - 解决方法：配置 ssh 隧道端口转发

`gauth.CommandLineAuth()` + 桌面应用凭据 =  `错误 400： invalid_request`
  - 错误详情：The redirect URI in the request, urn:ietf:wg:oauth:2.0:oob, can only be used by a Client ID for native application. It is not allowed for the WEB client type. 
 
`gauth.CommandLineAuth()` + Web 应用凭据 =  `错误 400： redirect_uri_mismatch`
- 错误详情：The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow migration guide linked in the developer docs below to migrate your app to an alternative method.

**Comment by wanyunr** [comment]
gauth.LocalWebserverAuth() + 桌面应用凭据 = 错误 400： invalid_request
然后我的错误详情是`redirect_uri=http://localhost:8080`，是隧道的问题吗

**Comment by Jared-02** [comment]
> gauth.LocalWebserverAuth() + 桌面应用凭据 = 错误 400： invalid_request 然后我的错误详情是`redirect_uri=http://localhost:8080`，是隧道的问题吗

这应该不是隧道的问题，隧道配置错误是找不到 `localhost:8080`。首先你应该使用 **Web 应用凭据**，试试重新创建一个凭据看看？记得更换服务器上的 `client_secrets.json`，并且删除过时的 `credentials.json`。

**Comment by wanyunr** [comment]
今天再次尝试，使用 桌面应用凭据 成功了😂
把发布状态改到测试版，再改回来，就成功了
![Clip_2024-03-18_13-03-42](https://github.com/Jared-02/auto-backup/assets/105478325/0596e63d-59c6-4c90-86a4-fd55405a6503)


先观察几天，看授权会不会掉

**Comment by Jared-02** [comment]
> 今天再次尝试，使用 桌面应用凭据 成功了😂 把发布状态改到测试版，再改回来，就成功了
> ...

解决了就好 :wink:

**Comment by Jared-02** [comment]
fixed in https://github.com/Jared-02/auto-backup/commit/c8ed9a436f808a287afe8588b3979ff3323dfbc3
